baseurl: /edmonton
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: edmonton
github_org: maptime
maptime:
  chapter: MaptimeYEG
  twitter: MaptimeYEG
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
